"""
    Routing: what algebra does this Hamiltonian generate, and which branch does it take.

    Everything about the algebra itself is PauLie's answer. This module only decides
    where to send it, and splits it where the split is exact.
"""

from paulie.classifier.classification import Classification
from paulie.common.pauli_string_collection import PauliStringCollection
from paulie.common.pauli_string_linear import PauliStringLinear
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import connected_components

from lizzy.hamiltonian import anticommutation_matrix, terms_of

# DLA classification depends on generator words, not coefficients or input order.
# ``free_part`` revisits the same growing subsets, so cache those structural answers.
_classification_cache: dict[tuple[str, ...], Classification] = {}
_CLASSIFICATION_CACHE_SIZE = 4096


def classify(hamiltonian: PauliStringLinear) -> Classification:
    """
    Classify the dynamical Lie algebra generated by a Hamiltonian's terms.

    Args:
        hamiltonian (PauliStringLinear): The Hamiltonian.
    Returns:
        Classification: PauLie's classification, unwrapped. Ask it for
        ``get_algebra()``, ``get_dla_dim()``, ``get_orthogonal_size()`` and the rest.
    """
    paulis = [p for _, p in terms_of(hamiltonian)]
    key = tuple(sorted(str(pauli) for pauli in paulis))
    if key not in _classification_cache:
        if len(_classification_cache) >= _CLASSIFICATION_CACHE_SIZE:
            _classification_cache.pop(next(iter(_classification_cache)))
        _classification_cache[key] = PauliStringCollection(paulis).get_class()
    return _classification_cache[key]


def is_fast_forwardable(classification: Classification, n_qubits: int) -> bool:
    r"""
    Apply the static router's algebra-dimension budget.

    The historical name refers to a heuristic cutoff :math:`d \leq 8n^2` for this
    instance, not a proof of asymptotic fast-forwardability. The supported
    Givens :math:`so(m)` route uses at most :math:`d=m(m-1)/2` rotations, but a small
    dimension alone does not establish a compatible representation or make that
    route cheaper than a product formula.

    Args:
        classification (Classification): The classified algebra.
        n_qubits (int): Number of qubits the Hamiltonian acts on.
    Returns:
        bool: True if the algebra's dimension fits the routing budget.
    """
    return classification.get_dla_dim() <= 8 * n_qubits**2


def summands(hamiltonian: PauliStringLinear) -> list[PauliStringLinear]:
    r"""
    Split a Hamiltonian into parts whose time evolutions commute exactly.

    Two Pauli strings in different connected components of the anticommutation graph
    commute by construction, so

    .. math::

        e^{-itH} = \prod_i e^{-itH_i}

    holds exactly, with no Trotter error between the parts. Each part also generates
    its own DLA summand, so it can be classified, routed and compiled on its own -- and
    on its own qubit support, which is usually much smaller than the whole register.

    Args:
        hamiltonian (PauliStringLinear): The Hamiltonian.
    Returns:
        list[PauliStringLinear]: The parts, in descending order of term count. A
        Hamiltonian whose graph is connected is returned unchanged, as a single part.
    """
    terms = terms_of(hamiltonian)
    paulis = [p for _, p in terms]

    adjacency = anticommutation_matrix(paulis)
    count, labels = connected_components(csr_matrix(adjacency), directed=False)
    if count <= 1:
        return [hamiltonian]

    grouped: dict[int, list[tuple[complex, str]]] = {}
    for index, label in enumerate(labels):
        grouped.setdefault(int(label), []).append(
            (terms[index][0], str(terms[index][1]))
        )
    # Sorted twice over: a benchmark that reports gate counts has to produce the same
    # ones on every run. Both orders are decided on the words, which are in hand here
    # -- rendering each part as a string to compare parts costs more than the split
    # itself on a six-hundred-term Hamiltonian, and the words already separate them,
    # since a Pauli belongs to exactly one component.
    ordered = sorted(
        (sorted(group, key=lambda term: term[1]) for group in grouped.values()),
        key=lambda group: (-len(group), [word for _, word in group]),
    )
    return [PauliStringLinear(group) for group in ordered]
